sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: o0hBm6ktX7ISMhHOcH9Po5YPZzL2teuwleNkU/jNl2fcZ38k75bQ6KhijG1be5IwBJiOYQIOAE9B6q7ZKdnzlGRO/L2xFYiBAdr8hjarilWkSaN9htIMama3xg79VLEvoACmy16gkojtlcJ0EiGhUFdn6KuwTOG2E9BYq/ESQ4Uiaj4DhbUUAZvNdMZk/2UQn3f2+Gg9PAhb0brCiq8inTBy6t4ZnyIPNSB4D7EOfD454Ldkoh1vGRvvakYewlcPNzBLNYNi6sLsbhVKkaRCweZCNsTf2RpN/XkTWqNCR0R1GFMu/jmZRn7XWaD2KWgzc4xLhCynZBsO+coOZnb02zzpgqcb/OrfUcnaHwPCSxI+nvyYNtOlo/FLstwm+2dZ1/kdxjIz3H/ThAYDktmjyXeBKd48x21msOoZHgUkPxVZwpkJyyD6EWTdKTb4NcSZwDBCzPDI+15EeVnCIE4hJt80N3i8CFuS/ZqgPHSRvQidLlyOqM/njdK2fYLF/8K/zebrwSnYlBlpU/2JvsKayifLexDLJKQBsJkFgAFke8Mg4PSUfFSxf8D2rSpWJu+0tUIvI4p0RRrsmHmV2/lB3iPrDN6zd1EU4xCpfNFzrG797dcbRzN/h6bsTQfXBzX9Wr8Hoi4XAR81x0OcGIxmkHossw5tx+0Gn7K8/2kCAt8=
  - secure: mCGqxBDmLmHcNK6E/MJwuwXsljSh9rum0X8TuB+40Cd9yIvtj9VdyoKCwOFqw8rMMQ+yo90oMsJ1f0IH2HhCZXbtjKn/Lv1lT+JPeOa0I7BCnYkJnIvAinY0ujMXmExN0jrUqnr271g5F7lhq3wseOqXWcgPfzRaPfjEdFGulQjzYfZIANt9mci/FgXVevQfCvcZWyW/HRyrhnhpIw41pNKnWmMyDorZX+PbQbn7EHnOuEsCCy9ixzFf9hVJZx7cBFj1VLov+f2DT31jL0ZFv09QkExzyF4pxnZk4noGMFb1qThY6oSE78AlYYT25CcT4aDWmJ9JzpsNPBUddfhUr4bFO4VP/wU1Xu2p/Rg9xQQs2y6t8Vsr5i3odKFtWCF8CHnXu9Aas1Nx8l3XTPifxqMSiIrqaioKmmsIy6idV2OrkmN+y8FPV8apJzTxVd1K/fReEjk/PS2DaUgVOd1MWcgOenp52mAiyGZxoja4wiI0dwONtqz0W85SAZEIM4FxTI5AyLgIdlpBTLoKUQ87oAH0W15TMtMDxUbEUorKMeoh+0ACpGIyE8bDE2nS6kSTC1+3rDWL+tNPNLhLdsp2fn+LjdMTjwiDmZITZofFjbYDfMbbhsHXQyir1m7xSUIy6kwMuZ+HYxlIhzUKMAemmsy76KKIyIeGORpUeLs/y6M=
  - secure: IxsCz2XsMnwAZRLEbJ8CckrUUkzfLhVI0HQNoay7bN08taTkRMjV+Wr6n10Q4JUYKZEwfg5q33IJxQdaVneqi2ceDXZqrmP1Z8pqrcO3PE7T6I6V1koHP7zKobUJjjhN6DbdxRsBb3G8AGBH5rBacPFbek1YUxnjALF5Evke/rgfvt25M9jreGvTvawZ9rDJDrxNKOV1g8uu3hAkiXm2U1ey0Vr5Y5w1bP3F3IYBdvdLSu66BBAJpcL7KyAC8cPxIK8WuMgN8a0aae2qUXeZMkN4k6OKtZYLfRkWDr4738LGjBEWslnJPBKPzwt/c7qu83ADwy2XfLGJVLKZFOTSGcxsi4oe4Fc873SXSlFuL3nI5yllGm0BWdf5DNYDVevALp1mXLYw85XBsL+w6+5tNQAd8tEwYZ/najqo/2mTEPwGu45cJNFw2hCLyjBqbSaeXxpmipTROxwkXtvJRKTxDoMOY1vCTNLYOtBtumJPfT5lI7wTo2LGHziomRYQPL9qKXfraLYi78jxa55j0F58noYzIfuWkMufJd1Pka1tbLjsmpcISzvOsa7PTRhwG40sLsq8bhp8kl2b6USUXGo3rTvQOG/QM55FyH4JP2mjBkqsuIGotDMAw1Z2dRU5Ops+gOCtI/oytgdE+ekSxp0TY8qAukJfgosAGTgiwX34hcU=
  - secure: kMjXMB8350ljESbl+cxAklkNnN6AZ5WUvx/juP6curabex8RqsxbVulToqXIAbcH8UyXUoLRuIXT/uQm9ELiq3noGtgpc0/BCTHQZwXF3fTj9SEjYGvuHeNfdMy3it6Jv7k5++MP1QHK2K3H8QEfDirqyvp3ln44dGz1wq7Lgowd3UIj3lzoL3RRbF4o4CdyjZpUl7fr/fUc6IiD27cRMOwKmnBy1pVIDfDb55BFK54q4UKz7xQpMBdsWtALJ/v/J5o9txxixrep5sOGJuOojrx//ZQgkZoFZMcr+OkoaY76WQxkdA0l0QngY7pQ9dUd5+lQbzR00tE9Q+9i6Tdx2RKHJm42R1kjQ1QGiX0IME0f/2ILIeQ8VgYqD5hOFT7o4ms+izWcl2wgOcf5frkTc+goyAfCzSIrbef0CQQx8xEmqMCSnxD/YCxpUPxKYsuB3ivjj0BizbwQvlnrPhPNSmJu6UYGWf8PlvCOCPwMJLoiC/VdaWOKku5E7hydECNXxVOVhQGLnBQxh6Z77qd4DbtOp2OoSaOjoB3zw2h1f8xe+xGwLTthAdNoU5h9d+2bJkmxPO+5EQXXSdZ1dqoxMZJcAJnlM1xsWpH1SmXekjNnqfH2dwnKekF9uNjesuCKI6thvIpRzsxjQp83mUnXs0JdmyfQc9eRV5vcmbZOOug=
